### ISSUE TITLE
login over http

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-cordova-app#1]
If i understand this correctly:
https://github.com/openfoodfacts/cordova-app/blob/master/www/index.html#L107

The login is done over http.
Could you get an ssl certificate so login aren't done in clear over the wire.

My point is that there is no way to know that from the app.
In a web browser, one can see it is not going https.

**Comment by stephanegigandet** [comment]
I now have a domain validated certificate for openfoodfacts.org
I will try to use it for opening sessions and receiving an authentification cookie.
Besides authentification, the rest of the site will stay in http as we don't have a wildcard certificate and we use hundreds of subdomains.

**Comment by teolemon** [comment]
We have switched to HTTPS

**Comment by teolemon** [comment]
Code changes were merged for this. Needs to be deployed.

**Comment by teolemon** [comment]
Should be fixed @stephanegigandet
