### ISSUE TITLE
Warn visitors when the product page they're viewing hasn't be updated for 18 months, and add it to a todo list

### ISSUE THREAD

**Issue by bcatelin** [openfoodfacts/openfoodfacts-cordova-app#14]
related to https://github.com/openfoodfacts/openfoodfacts-server/issues/58 
When using the app users need to be alerted that the engtry is old. if the user is a contributor then the user should have a way to add it to their todo list (for instance by making it appear in their 'products you have added that need to be completed' page). Perhaps by being proposed a check box and a 'save' button to do so. so that contributors who want to check if anything changed later on, like atg home, can easily do so.

**Comment by bcatelin** [comment]
test to see how it behaves when closed and linked to another issue

**Comment by teolemon** [comment]
It can be done server side @stephanegigandet  ?
