### ISSUE TITLE
Unable to build | iOS 

### ISSUE THREAD

**Issue by adamjbradley** [openfoodfacts/openfoodfacts-cordova-app#36]
Fails with the following error
$ cordova build ios --verbose
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform ios
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating platform-specific config.xml from defaults for iOS at /Projects/OpenFoodFacts/openfoodfacts-cordova-app/platforms/ios/OpenFoodFacts/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
Current launch storyboard undefined
Not changing launch storyboard setting in info plist.
Wrote out iOS Bundle Identifier "org.openfoodfacts.scanner" and iOS Bundle Version "2.5.0" to /Projects/OpenFoodFacts/openfoodfacts-cordova-app/platforms/ios/OpenFoodFacts/OpenFoodFacts-Info.plist
No need to update build settings for launch storyboard support.
iOS Product Name has not changed (still "OpenFoodFacts")
Updating icons at platforms/ios/OpenFoodFacts/Images.xcassets/AppIcon.appiconset/
This app does not have splash screens defined
Updating launch storyboard images at platforms/ios/OpenFoodFacts/Images.xcassets/LaunchStoryboard.imageset/
Updating Storyboard image set contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
No scripts found for hook "after_prepare".
No scripts found for hook "before_compile".
Error: 
`

**Comment by teolemon** [comment]
should be fixed. feel free to reopen otherwise
